services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: root
      MYSQL_PASSWORD: Lmao123789
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "4306:3306"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: bao
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:90"
    restart: always
    depends_on:
      - backend

volumes:
  db_data:
