name: Fullstack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bao
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install and build React client
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Install and test backend
      - name: Setup backend
        working-directory: ./backend
        run: |
          npm install
          # Cấu hình ENV biến nếu cần
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=" >> .env
          echo "DB_NAME=bao" >> .env
          echo "PORT=" >> .env
          npm run test  # hoặc `npm start` nếu chỉ muốn khởi động server